name: Unit Test

on:
  pull_request:
    branches:
      - 'develop'
    types: [ opened, synchronize, reopened ]

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Create applicaton.yml file
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML_TEST }}" > src/main/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build test --no-daemon